7,1,1,1000,"Example 6 - Linear regression"
"POM-QM for Windows 3.0 Build 11"
6,5,10,-1,0,0,0
0,1,0,0,1,0,0
4,#TRUE#,0,0,0,0,0,0
6,2
""
"Umbrella"
"Time(x)"
"Weights->"
"Winter"
"Spring"
"Summer"
"Fall"
"TOTALS"
"AVERAGE"
2
Weights->, 5  0  0 
Winter, 0  652  20 
Spring, 0  673  24 
Summer, 0  457  16 
Fall, 0  640  21 
TOTALS, 0  2422  81 
AVERAGE, 0  605.5  20.25 
-1,-1
"done"
"This problem could also be solved by using the linear regression submodel rather than the time-series submodel."
